import xml.etree.ElementTree as ET
from parser_studio.generator import generate_parser

BASIC_META = {
    "name": "TestParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Acme", "model": "Firewall", "version": "ANY",
    "anchor": "ACME_FW",
}

BASIC_MAPPINGS = {
    "srcip": "srcIpAddr",
    "dstip": "destIpAddr",
    "action": "eventAction",
}


def _wrap(fragment: str) -> ET.Element:
    """Wrap a parser fragment in <eventParser> so ET can parse it."""
    return ET.fromstring(f"<eventParser>{fragment}</eventParser>")


def test_generates_parseable_fragment():
    """Generated output must be parseable when wrapped in <eventParser>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    root = _wrap(xml_str)   # must not raise
    assert root is not None

def test_fragment_has_pattern_definitions():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<patternDefinitions>" in xml_str

def test_recognizer_before_pattern_definitions():
    """<eventFormatRecognizer> must appear before <patternDefinitions>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert xml_str.index("<eventFormatRecognizer>") < xml_str.index("<patternDefinitions>")

def test_recognizer_is_single_line():
    """<eventFormatRecognizer> must open and close on the same line (no nesting)."""
    for line in generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", []).splitlines():
        if "<eventFormatRecognizer>" in line:
            assert "</eventFormatRecognizer>" in line
            break

def test_no_studio_header_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "Generated by Parser Studio" not in xml_str

def test_fragment_has_no_event_parser_wrapper():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<eventParser" not in xml_str

def test_fragment_has_no_device_type():
    """Metadata is stored in DB columns, not in the XML fragment."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<Vendor>" not in xml_str
    assert "<deviceType>" not in xml_str

def test_json_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, {"threatName": "msg"}, "syslog+json", [])
    assert "collectAndSetAttrByJSON" in xml_str

def test_kv_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "collectAndSetAttrByKeyValuePair" in xml_str

def test_xml_format_uses_xpath():
    xml_str = generate_parser(BASIC_META, {"Event.System.EventID": "winEventId"}, "syslog+xml", [])
    assert "collectFieldsByXPath" in xml_str

def test_no_double_dash_in_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    import re
    assert not re.search(r'<!--.*?--.*?-->', xml_str)

def test_has_event_severity_default():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventSeverity"' in xml_str

def test_has_event_type():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventType"' in xml_str


_APACHE_SAMPLES = [
    '<142>Sep 17 13:27:37 example.com ApacheLog   192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<142>Sep 17 13:27:37 example.com ApacheLog 0  192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<182>Mar 22 19:00:14 lab1.example.com Apache_ErrorLog: [Tue Mar 22 16:17:41.711593 2022] [proxy_http:error]',
]

_TEXT_META = {
    "name": "ApacheParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Apache", "model": "Apache", "version": "ANY",
    "anchor": "",  # blank -- should be auto-detected
}


def test_syslog_pri_prepended_when_samples_have_pri():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", _APACHE_SAMPLES)
    assert "gPatSyslogPRI" in xml_str

def test_syslog_pri_not_added_without_pri_samples():
    no_pri = ["Jul 23 10:05:15 2025 fw01 192.168.1.1 srcip=10.0.0.5"]
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", no_pri)
    assert "gPatSyslogPRI" not in xml_str

def test_header_regex_no_colon_space_separator():
    r"""[:\s]+ must not appear in the header_regex - it blocks body capture."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "[:\\s]+" not in xml_str and "[:\\\\s]+" not in xml_str

def test_pri_in_both_recognizer_and_header_regex():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+text", _APACHE_SAMPLES)
    lines = xml_str.splitlines()
    recognizer_line = next(l for l in lines if "eventFormatRecognizer" in l)
    assert "gPatSyslogPRI" in recognizer_line
    # Both the recognizer line AND a non-recognizer line (header regex CDATA) must contain gPatSyslogPRI
    lines_with_pri = [l for l in xml_str.splitlines() if "gPatSyslogPRI" in l]
    assert len(lines_with_pri) >= 2, "gPatSyslogPRI must appear in both recognizer and header regex"


def test_apache_tag_detected_in_recognizer():
    """Consistent 'ApacheLog' token from samples appears in recognizer."""
    xml_str = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    assert "ApacheLog" in xml_str


def test_explicit_anchor_not_overridden():
    """If meta['anchor'] is explicitly set, it must not be replaced by auto-detection."""
    meta_with_anchor = {**_TEXT_META, "anchor": "MY_CUSTOM_ANCHOR"}
    xml_str = generate_parser(meta_with_anchor, {}, "syslog+text", _APACHE_SAMPLES)
    assert "MY_CUSTOM_ANCHOR" in xml_str


def test_no_consistent_tag_falls_back_to_name():
    """If samples have no consistent tag, parser name-based anchor is used."""
    diverse = [
        "Jul 23 10:05:15 2025 fw01 192.168.1.1 FOO srcip=1.1.1.1",
        "Jul 23 10:05:15 2025 fw01 192.168.1.1 BAR srcip=2.2.2.2",
    ]
    xml_str = generate_parser(_TEXT_META, {}, "syslog+kv", diverse)
    # Should fall back to APACHEPARSER (name uppercased) since anchor is blank
    assert "APACHEPARSER" in xml_str


# ── Task 3: switch/case scaffold ─────────────────────────────────────────────

_ACCESS_LOG_SAMPLES = [
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "192.168.20.35 - - [23/Jul/2025:10:05:15 -0700] "
    '"GET /index.html HTTP/1.1" 200 1234',
    "Jul 23 10:06:00 2025 web01 192.168.1.1 "
    "10.0.0.5 - - [23/Jul/2025:10:06:00 -0700] "
    '"POST /api HTTP/1.1" 201 56',
]

_ERROR_LOG_SAMPLES = [
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "[Thu Jul 23 10:05:15.123456 2025] [proxy_http:error] [pid 12345] message here",
    "Jul 23 10:06:00 2025 web01 192.168.1.1 "
    "[Thu Jul 23 10:06:00.654321 2025] [auth:warn] [pid 98765] another message",
]

_NGINX_ACCESS_SAMPLES = [
    "Jul 23 10:05:15 2025 nginx01 192.168.1.1 "
    "203.0.113.42 - - [23/Jul/2025:10:05:15 +0000] "
    '"GET /health HTTP/1.1" 200 2',
]

_TEXT_META_NO_ANCHOR = {
    "name": "WebParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Generic", "model": "WebServer", "version": "ANY", "anchor": "",
}


def test_syslog_text_generates_switch_case():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ACCESS_LOG_SAMPLES)
    assert "<switch>" in xml
    assert "<case>" in xml
    assert "<default/>" in xml


def test_access_log_body_generates_srcIpAddr_capture():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ACCESS_LOG_SAMPLES)
    assert "srcIpAddr" in xml
    assert "gPatIpAddr" in xml


def test_error_log_body_generates_bracket_pattern():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ERROR_LOG_SAMPLES)
    assert "<switch>" in xml
    # error_log case uses bracket pattern
    assert "\\[<:gPatMesgBodyMin>\\]" in xml


def test_switch_case_works_for_any_device_type():
    """switch/case scaffold is device-type agnostic (Nginx access logs here)."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NGINX_ACCESS_SAMPLES)
    assert "<switch>" in xml
    assert "srcIpAddr" in xml  # access log → IP capture present
