import xml.etree.ElementTree as ET
from parser_studio.generator import generate_parser

BASIC_META = {
    "name": "TestParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Acme", "model": "Firewall", "version": "ANY",
    "anchor": "ACME_FW",
}

BASIC_MAPPINGS = {
    "srcip": "srcIpAddr",
    "dstip": "destIpAddr",
    "action": "eventAction",
}


def _wrap(fragment: str) -> ET.Element:
    """Wrap a parser fragment in <eventParser> so ET can parse it."""
    return ET.fromstring(f"<eventParser>{fragment}</eventParser>")


def test_generates_parseable_fragment():
    """Generated output must be parseable when wrapped in <eventParser>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    root = _wrap(xml_str)   # must not raise
    assert root is not None

def test_fragment_has_pattern_definitions():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<patternDefinitions>" in xml_str

def test_recognizer_before_pattern_definitions():
    """<eventFormatRecognizer> must appear before <patternDefinitions>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert xml_str.index("<eventFormatRecognizer>") < xml_str.index("<patternDefinitions>")

def test_recognizer_is_single_line():
    """<eventFormatRecognizer> must open and close on the same line (no nesting)."""
    for line in generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", []).splitlines():
        if "<eventFormatRecognizer>" in line:
            assert "</eventFormatRecognizer>" in line
            break

def test_no_studio_header_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "Generated by Parser Studio" not in xml_str

def test_fragment_has_no_event_parser_wrapper():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<eventParser" not in xml_str

def test_fragment_has_no_device_type():
    """Metadata is stored in DB columns, not in the XML fragment."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<Vendor>" not in xml_str
    assert "<deviceType>" not in xml_str

def test_json_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, {"threatName": "msg"}, "syslog+json", [])
    assert "collectAndSetAttrByJSON" in xml_str

def test_kv_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "collectAndSetAttrByKeyValuePair" in xml_str

def test_xml_format_uses_xpath():
    xml_str = generate_parser(BASIC_META, {"Event.System.EventID": "winEventId"}, "syslog+xml", [])
    assert "collectFieldsByXPath" in xml_str

def test_no_double_dash_in_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    import re
    assert not re.search(r'<!--.*?--.*?-->', xml_str)

def test_has_event_severity_default():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventSeverity"' in xml_str

def test_has_event_type():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventType"' in xml_str


_APACHE_SAMPLES = [
    '<142>Sep 17 13:27:37 example.com ApacheLog   192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<142>Sep 17 13:27:37 example.com ApacheLog 0  192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<182>Mar 22 19:00:14 lab1.example.com Apache_ErrorLog: [Tue Mar 22 16:17:41.711593 2022] [proxy_http:error]',
]

def test_syslog_pri_prepended_when_samples_have_pri():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", _APACHE_SAMPLES)
    assert "gPatSyslogPRI" in xml_str

def test_syslog_pri_not_added_without_pri_samples():
    no_pri = ["Jul 23 10:05:15 2025 fw01 192.168.1.1 srcip=10.0.0.5"]
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", no_pri)
    assert "gPatSyslogPRI" not in xml_str

def test_header_regex_no_colon_space_separator():
    r"""[:\s]+ must not appear in the header_regex - it blocks body capture."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "[:\\s]+" not in xml_str and "[:\\\\s]+" not in xml_str

def test_pri_in_both_recognizer_and_header_regex():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+text", _APACHE_SAMPLES)
    lines = xml_str.splitlines()
    recognizer_line = next(l for l in lines if "eventFormatRecognizer" in l)
    assert "gPatSyslogPRI" in recognizer_line
    # Both the recognizer line AND a non-recognizer line (header regex CDATA) must contain gPatSyslogPRI
    lines_with_pri = [l for l in xml_str.splitlines() if "gPatSyslogPRI" in l]
    assert len(lines_with_pri) >= 2, "gPatSyslogPRI must appear in both recognizer and header regex"
