import xml.etree.ElementTree as ET
from parser_studio.generator import generate_parser

BASIC_META = {
    "name": "TestParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Acme", "model": "Firewall", "version": "ANY",
    "anchor": "ACME_FW",
}

BASIC_MAPPINGS = {
    "srcip": "srcIpAddr",
    "dstip": "destIpAddr",
    "action": "eventAction",
}


def _wrap(fragment: str) -> ET.Element:
    """Wrap a parser fragment in <eventParser> so ET can parse it."""
    return ET.fromstring(f"<eventParser>{fragment}</eventParser>")


def test_generates_parseable_fragment():
    """Generated output must be parseable when wrapped in <eventParser>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    root = _wrap(xml_str)   # must not raise
    assert root is not None

def test_fragment_has_pattern_definitions():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<patternDefinitions>" in xml_str

def test_recognizer_before_pattern_definitions():
    """<eventFormatRecognizer> must appear before <patternDefinitions>."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert xml_str.index("<eventFormatRecognizer>") < xml_str.index("<patternDefinitions>")

def test_recognizer_is_single_line():
    """<eventFormatRecognizer> must open and close on the same line (no nesting)."""
    for line in generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", []).splitlines():
        if "<eventFormatRecognizer>" in line:
            assert "</eventFormatRecognizer>" in line
            break

def test_no_studio_header_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "Generated by Parser Studio" not in xml_str

def test_fragment_has_no_event_parser_wrapper():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<eventParser" not in xml_str

def test_fragment_has_no_device_type():
    """Metadata is stored in DB columns, not in the XML fragment."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "<Vendor>" not in xml_str
    assert "<deviceType>" not in xml_str

def test_json_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, {"threatName": "msg"}, "syslog+json", [])
    assert "collectAndSetAttrByJSON" in xml_str

def test_kv_format_uses_correct_extraction():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "collectAndSetAttrByKeyValuePair" in xml_str

def test_xml_format_uses_xpath():
    xml_str = generate_parser(BASIC_META, {"Event.System.EventID": "winEventId"}, "syslog+xml", [])
    assert "collectFieldsByXPath" in xml_str

def test_no_double_dash_in_comments():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    import re
    assert not re.search(r'<!--.*?--.*?-->', xml_str)

def test_has_event_severity_default():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventSeverity"' in xml_str

def test_has_event_type():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert 'attr="eventType"' in xml_str


_APACHE_SAMPLES = [
    '<142>Sep 17 13:27:37 example.com ApacheLog   192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<142>Sep 17 13:27:37 example.com ApacheLog 0  192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
    '<182>Mar 22 19:00:14 lab1.example.com Apache_ErrorLog: [Tue Mar 22 16:17:41.711593 2022] [proxy_http:error]',
]

_TEXT_META = {
    "name": "ApacheParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Apache", "model": "Apache", "version": "ANY",
    "anchor": "",  # blank -- should be auto-detected
}


def test_syslog_pri_prepended_when_samples_have_pri():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", _APACHE_SAMPLES)
    assert "gPatSyslogPRI" in xml_str

def test_syslog_pri_not_added_without_pri_samples():
    no_pri = ["Jul 23 10:05:15 2025 fw01 192.168.1.1 srcip=10.0.0.5"]
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", no_pri)
    assert "gPatSyslogPRI" not in xml_str

def test_header_regex_no_colon_space_separator():
    r"""[:\s]+ must not appear in the header_regex - it blocks body capture."""
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "[:\\s]+" not in xml_str and "[:\\\\s]+" not in xml_str

def test_pri_in_both_recognizer_and_header_regex():
    xml_str = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+text", _APACHE_SAMPLES)
    lines = xml_str.splitlines()
    recognizer_line = next(l for l in lines if "eventFormatRecognizer" in l)
    assert "gPatSyslogPRI" in recognizer_line
    # Both the recognizer line AND a non-recognizer line (header regex CDATA) must contain gPatSyslogPRI
    lines_with_pri = [l for l in xml_str.splitlines() if "gPatSyslogPRI" in l]
    assert len(lines_with_pri) >= 2, "gPatSyslogPRI must appear in both recognizer and header regex"


def test_apache_tag_detected_in_recognizer():
    """Consistent 'ApacheLog' token from samples appears in recognizer."""
    xml_str = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    assert "ApacheLog" in xml_str


def test_explicit_anchor_not_overridden():
    """If meta['anchor'] is explicitly set, it must not be replaced by auto-detection."""
    meta_with_anchor = {**_TEXT_META, "anchor": "MY_CUSTOM_ANCHOR"}
    xml_str = generate_parser(meta_with_anchor, {}, "syslog+text", _APACHE_SAMPLES)
    assert "MY_CUSTOM_ANCHOR" in xml_str


def test_no_consistent_tag_falls_back_to_name():
    """If samples have no consistent tag, parser name-based anchor is used."""
    diverse = [
        "Jul 23 10:05:15 2025 fw01 192.168.1.1 FOO srcip=1.1.1.1",
        "Jul 23 10:05:15 2025 fw01 192.168.1.1 BAR srcip=2.2.2.2",
    ]
    xml_str = generate_parser(_TEXT_META, {}, "syslog+kv", diverse)
    # Should fall back to APACHEPARSER (name uppercased) since anchor is blank
    assert "APACHEPARSER" in xml_str


# ── Task 3: switch/case scaffold ─────────────────────────────────────────────

_ACCESS_LOG_SAMPLES = [
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "192.168.20.35 - - [23/Jul/2025:10:05:15 -0700] "
    '"GET /index.html HTTP/1.1" 200 1234',
    "Jul 23 10:06:00 2025 web01 192.168.1.1 "
    "10.0.0.5 - - [23/Jul/2025:10:06:00 -0700] "
    '"POST /api HTTP/1.1" 201 56',
]

_ERROR_LOG_SAMPLES = [
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "[Thu Jul 23 10:05:15.123456 2025] [proxy_http:error] [pid 12345] message here",
    "Jul 23 10:06:00 2025 web01 192.168.1.1 "
    "[Thu Jul 23 10:06:00.654321 2025] [auth:warn] [pid 98765] another message",
]

_NGINX_ACCESS_SAMPLES = [
    "Jul 23 10:05:15 2025 nginx01 192.168.1.1 "
    "203.0.113.42 - - [23/Jul/2025:10:05:15 +0000] "
    '"GET /health HTTP/1.1" 200 2',
]

_TEXT_META_NO_ANCHOR = {
    "name": "WebParser", "scope": "enabled", "parser_type": "User",
    "vendor": "Generic", "model": "WebServer", "version": "ANY", "anchor": "",
}


def test_syslog_text_generates_switch_case():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ACCESS_LOG_SAMPLES)
    assert "<switch>" in xml
    assert "<case>" in xml
    assert "<default/>" in xml


def test_access_log_body_generates_srcIpAddr_capture():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ACCESS_LOG_SAMPLES)
    assert "srcIpAddr" in xml
    assert "gPatIpAddr" in xml


def test_error_log_body_generates_bracket_pattern():
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ERROR_LOG_SAMPLES)
    assert "<switch>" in xml
    # error_log case uses bracket pattern
    assert "\\[<:gPatMesgBodyMin>\\]" in xml


def test_switch_case_works_for_any_device_type():
    """switch/case scaffold is device-type agnostic (Nginx access logs here)."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NGINX_ACCESS_SAMPLES)
    assert "<switch>" in xml
    assert "srcIpAddr" in xml  # access log → IP capture present


# ── Header structure detection (year / IP auto-detection) ─────────────────────

def test_apache_style_header_omits_year_and_ip():
    """Apache logs have no year or IP in syslog header; generated recognizer must not include them."""
    xml = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    # Split on the recognizer line and check the tokens present / absent
    rec_line = next(l for l in xml.splitlines() if "eventFormatRecognizer" in l)
    assert "gPatYear" not in rec_line, "recognizer should not contain gPatYear for Apache-style logs"
    assert "gPatIpAddr" not in rec_line, "recognizer should not contain gPatIpAddr for Apache-style logs"


def test_sentinelone_style_header_includes_year_and_ip():
    """SentinelOne KV logs have year + IP in syslog header; generated recognizer must include them."""
    s1 = "Jul 23 10:05:15 2025 host 1.2.3.4 srcip=10.0.0.5 dstip=8.8.8.8"
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [s1])
    rec_line = next(l for l in xml.splitlines() if "eventFormatRecognizer" in l)
    assert "gPatYear" in rec_line
    assert "gPatIpAddr" in rec_line


def test_apache_style_header_no_year_skips_datetime_step():
    """When no year in syslog header, Step 2 must not emit toDateTime with $_year."""
    xml = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    assert "toDateTime($_mon, $_day, $_year" not in xml


_MIXED_BODY_SAMPLES = [
    # access_log body
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "192.168.20.35 - - [23/Jul/2025:10:05:15 -0700] \"GET /index.html HTTP/1.1\" 200 1234",
    # error_log body
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "[Thu Jul 23 10:05:15.123456 2025] [proxy_http:error] [pid 12345] message here",
    # generic body (unstructured text, no IP or bracket at start)
    "Jul 23 10:05:15 2025 web01 192.168.1.1 "
    "Some random unstructured message that has no access or error log pattern",
]


def test_generic_case_always_last_in_switch():
    """When samples produce access_log, error_log and generic bodies, generic must be last."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _MIXED_BODY_SAMPLES)
    assert "<switch>" in xml
    generic_pos = xml.find("Generic text")
    error_pos   = xml.find("Error log")
    access_pos  = xml.find("NCSA Combined")
    assert generic_pos != -1, "generic case must be present"
    assert access_pos  < generic_pos, "access_log case must come before generic"
    assert error_pos   < generic_pos, "error_log case must come before generic"


def test_access_log_regex_extracts_http_fields():
    """Access log switch case must capture httpMethod, uriStem, httpStatusCode."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ACCESS_LOG_SAMPLES)
    assert "httpMethod"     in xml
    assert "uriStem"        in xml
    assert "httpStatusCode" in xml
    assert "recvBytes64"    in xml


def test_error_log_regex_extracts_log_level():
    """Error log switch case must capture logLevel."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _ERROR_LOG_SAMPLES)
    assert "logLevel" in xml


def test_access_log_with_leading_code_classified_as_access_log():
    """Body starting with '0  IP ...' (optional leading code) must generate access_log case."""
    xml = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    # Sample 2 has '0  192.168.20.35 ...' body; access_log case must be present
    assert "NCSA Combined" in xml


# ── Timestamp format support ──────────────────────────────────────────────────

def test_no_year_syslog_uses_3arg_todatetime():
    """When syslog header has no year, Step 2 must use 3-arg toDateTime (infers current year)."""
    xml = generate_parser(_TEXT_META, {}, "syslog+text", _APACHE_SAMPLES)
    assert "toDateTime($_mon, $_day, $_time)" in xml
    assert "toDateTime($_mon, $_day, $_year" not in xml


def test_year_syslog_uses_4arg_todatetime():
    """When syslog header has year, Step 2 must use 4-arg toDateTime."""
    s1 = "Jul 23 10:05:15 2025 host 1.2.3.4 srcip=10.0.0.5 dstip=8.8.8.8"
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [s1])
    assert "toDateTime($_mon, $_day, $_year, $_time)" in xml


def test_no_year_no_samples_uses_4arg_todatetime():
    """With no samples (safe default has_year=True), Step 2 uses 4-arg toDateTime."""
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "toDateTime($_mon, $_day, $_year, $_time)" in xml


def test_tz_in_syslog_header_uses_5arg_todatetime():
    """When syslog header has year + timezone, Step 2 must use 5-arg toDateTime."""
    sample = "Jul 23 10:05:15 2025 +0000 host 1.2.3.4 srcip=10.0.0.5"
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [sample])
    assert "toDateTime($_mon, $_day, $_year, $_time, $_tz)" in xml
    assert "gPatTimeZone" in xml


_JSON_TS_SAMPLE = (
    'Jul 23 10:05:15 2025 host 1.2.3.4 TAG: '
    '{"event":"login","timestamp":"2025-07-23T10:05:15.123456Z","srcip":"10.0.0.1"}'
)


def test_json_body_iso8601_microseconds_triggers_step3b():
    """JSON body with ISO 8601 microsecond timestamp field generates Step 3b deviceTime."""
    xml = generate_parser(BASIC_META, {"event": "eventType"}, "syslog+json", [_JSON_TS_SAMPLE])
    assert "Step 3b" in xml
    assert "toDateTime($timestamp" in xml
    assert "SSSSSS" in xml


def test_json_body_timestamp_format_string_correct():
    """The generated toDateTime format string matches the ISO 8601 microseconds pattern."""
    xml = generate_parser(BASIC_META, {"event": "eventType"}, "syslog+json", [_JSON_TS_SAMPLE])
    assert "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'" in xml


_KV_EPOCH_MS_SAMPLE = "Jul 23 10:05:15 2025 host 1.2.3.4 ts=1753264815000 srcip=10.0.0.1"


def test_kv_epoch_ms_body_timestamp_triggers_step3b():
    """KV body with 13-digit epoch 'ts' field generates Step 3b with divide()."""
    xml = generate_parser(BASIC_META, {"srcip": "srcIpAddr"}, "syslog+kv", [_KV_EPOCH_MS_SAMPLE])
    assert "Step 3b" in xml
    assert "divide($ts, 1000)" in xml
    assert "deviceTime" in xml


_KV_EPOCH_S_SAMPLE = "Jul 23 10:05:15 2025 host 1.2.3.4 timestamp=1753264815 srcip=10.0.0.1"


def test_kv_epoch_s_body_timestamp_triggers_step3b():
    """KV body with 10-digit epoch 'timestamp' field generates direct Step 3b assignment."""
    xml = generate_parser(BASIC_META, {"srcip": "srcIpAddr"}, "syslog+kv", [_KV_EPOCH_S_SAMPLE])
    assert "Step 3b" in xml
    assert "$timestamp" in xml
    assert "divide" not in xml


def test_no_body_timestamp_skips_step3b():
    """KV body without a timestamp field must not emit Step 3b."""
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "Step 3b" not in xml


def test_syslog_text_generic_body_skips_step3b():
    """syslog+text with no recognizable body timestamp must not emit Step 3b."""
    generic = ["Jul 23 10:05:15 2025 web01 192.168.1.1 some plain text message without a timestamp"]
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", generic)
    assert "Step 3b" not in xml


# ── NCSA body timestamp → Step 3b UTC deviceTime ─────────────────────────────

_NCSA_TS_SAMPLES = [
    "Sep 17 13:27:37 example.com WebLog "
    "192.168.20.35 - - [17/Sep/2009:13:27:37 -0700] "
    '"GET /icons/apache_pb2.gif HTTP/1.1" 200 2414',
]


def test_syslog_text_ncsa_timestamp_triggers_step3b():
    """syslog+text with NCSA access log timestamp generates Step 3b with TZ-aware deviceTime."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert "Step 3b" in xml
    assert "dd/MMM/yyyy:HH:mm:ss Z" in xml


def test_syslog_text_ncsa_step3b_when_guard():
    """Step 3b for NCSA syslog+text must use <when test='exist _req_time'> so error-log lines are unaffected."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert 'exist _req_time' in xml


def test_syslog_text_access_log_regex_captures_req_time():
    """Access log switch/case must capture _req_time (private) for the deviceTime Step 3b override."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert "_req_time:gPatMesgBodyMin" in xml


# ── Pure `text` format (no syslog header) ─────────────────────────────────────

_PURE_APACHE_SAMPLES = [
    '192.168.5.142 - - [04/Mar/2026:02:12:45 +0530] "POST /wp-login.php HTTP/1.1" 401 381 "-" "Mozilla/5.0 (Windows NT 10.0)"',
    '192.168.5.142 - - [04/Mar/2026:02:12:46 +0530] "GET /index.html HTTP/1.1" 200 512 "-" "Mozilla/5.0 (X11; Linux x86_64)"',
]

_TEXT_FORMAT_META = {
    "name": "ApacheAccess", "scope": "enabled", "parser_type": "User",
    "vendor": "Apache", "model": "HTTP", "version": "ANY", "anchor": "",
}


def test_text_format_access_log_recognizer():
    """fmt='text' with Apache access log samples must generate IP-based recognizer, not JSON stub."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    rec_line = next(l for l in xml.splitlines() if "eventFormatRecognizer" in l)
    assert "gPatIpAddr" in rec_line
    assert '"type"' not in rec_line


def test_text_format_ncsa_triggers_step3b():
    """fmt='text' with NCSA timestamp must generate Step 3b deviceTime override."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert "Step 3b" in xml
    assert "dd/MMM/yyyy:HH:mm:ss Z" in xml
    assert "exist _req_time" in xml


def test_ncsa_regex_captures_useragent():
    """NCSA access_log case must include optional combined-log userAgent capture."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert "userAgent:gPatMesgBodyMin" in xml


def test_ncsa_regex_useragent_in_text_format():
    """fmt='text' NCSA case must also include userAgent capture."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert "userAgent:gPatMesgBodyMin" in xml


def test_access_log_user_assignment_from_authuser():
    """syslog+text access log must emit <when exist _user> to assign user EAT."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert 'exist _user' in xml
    assert 'attr="user"' in xml


def test_text_format_user_assignment_from_authuser():
    """fmt='text' access log must also emit user assignment from _user."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert 'exist _user' in xml
    assert 'attr="user"' in xml


# ── HTTP status code conditional eventType ────────────────────────────────────

def test_access_log_uses_web_generic_default_eventtype():
    """Access log parser must use '{name}-Web-Generic' as default eventType, not '{name}-Event'."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert "ApacheAccess-Web-Generic" in xml
    assert "ApacheAccess-Event" not in xml


def test_access_log_generates_http_status_choose_block():
    """Access log parser must contain a <choose> block with HTTP status conditions."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert "<choose>" in xml
    assert "matches($httpStatusCode" in xml
    assert "ApacheAccess-Web-Request-Success" in xml
    assert "ApacheAccess-Web-Access-Denied" in xml
    assert "ApacheAccess-Web-Client-Error" in xml
    assert "ApacheAccess-Web-Server-Error" in xml


def test_access_log_choose_block_checks_specific_codes_before_generic():
    """401/403 must appear before generic '^4' so specific codes win."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    pos_401 = xml.index("^401")
    pos_403 = xml.index("^403")
    pos_4xx = xml.index("^4'")  # generic 4xx
    assert pos_401 < pos_4xx, "'^401' must appear before generic '^4'"
    assert pos_403 < pos_4xx, "'^403' must appear before generic '^4'"


def test_access_log_choose_guarded_by_exist_httpstatuscode():
    """The choose block must be wrapped in <when test='exist httpStatusCode'>."""
    xml = generate_parser(_TEXT_FORMAT_META, {}, "text", _PURE_APACHE_SAMPLES)
    assert 'exist httpStatusCode' in xml


def test_syslog_text_access_log_generates_http_status_choose():
    """syslog+text access log must also emit the HTTP status choose block."""
    xml = generate_parser(_TEXT_META_NO_ANCHOR, {}, "syslog+text", _NCSA_TS_SAMPLES)
    assert "<choose>" in xml
    assert "matches($httpStatusCode" in xml


def test_non_access_log_keeps_simple_eventtype():
    """Non-access-log formats must still use simple '{name}-Event' eventType."""
    xml = generate_parser(BASIC_META, BASIC_MAPPINGS, "syslog+kv", [])
    assert "TestParser-Event" in xml
    assert "<choose>" not in xml

def test_json_format_keeps_simple_eventtype():
    """JSON format must not generate HTTP status choose block."""
    json_meta = {**BASIC_META, "name": "MyJSON"}
    xml = generate_parser(json_meta, {}, "syslog+json", [])
    assert "MyJSON-Event" in xml
    assert "<choose>" not in xml
